# Kanonmaker - dva virtualni hosty nad jednim kodem.
# PHP bezi v kontejneru kanon-www, cesty jsou mapovane identicky.

<VirtualHost *:80>
        ServerAdmin kataindie@gmail.com
        ServerName kata.doma.slimak.cz
        DocumentRoot /data/www/kanonmaker/public

        ErrorLog ${APACHE_LOG_DIR}/error_log.kanonmaker
        CustomLog ${APACHE_LOG_DIR}/access_log.kanonmaker combined

        DirectoryIndex index.php

        <FilesMatch \.php$>
                SetHandler "proxy:fcgi://127.0.0.1:9058"
        </FilesMatch>

        <Directory /data/www/kanonmaker/public>
                AllowOverride All
                Require all granted
        </Directory>
</VirtualHost>

<VirtualHost *:80>
        ServerAdmin kataindie@gmail.com
        ServerName kata-admin.doma.slimak.cz
        DocumentRoot /data/www/kanonmaker/admin

        ErrorLog ${APACHE_LOG_DIR}/error_log.kanonmaker-admin
        CustomLog ${APACHE_LOG_DIR}/access_log.kanonmaker-admin combined

        DirectoryIndex index.php

        <FilesMatch \.php$>
                SetHandler "proxy:fcgi://127.0.0.1:9058"
        </FilesMatch>

        <Directory /data/www/kanonmaker/admin>
                AllowOverride All
                Require all granted
        </Directory>
</VirtualHost>
